version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: cimg/ruby:2.6.3
      - image: circleci/mysql:5.7
        environment:
          TZ: Asia/Tokyo
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_HOST: '%'
    steps:
      - checkout
      - run:
          name: Get mysql client
          command: apt-get install libmysqlclient-dev
      - ruby/bundle-install
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - run:
          name: rubocop
          command: bundle exec rubocop
      - run:
          name: rspec
          command: bundle exec rspec
