version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: cimg/ruby:2.6.3
      - image: circleci/mysql:5.7
        environment:
          TZ: Asia/Tokyo
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_HOST: '%'
    steps:
      - checkout
      - run:
          name: Get mysql client
          command: |
            apt-get update -y && apt-get install libmysqlclient-dev -y
      # bundle
      - restore_cache:
          keys:
            - vendor-bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: bundle check
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
      - save_cache:
          key: vendor-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      # yarn
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
      - run:
          name: yarn
          command: yarn install
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      # db
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - run:
          name: rubocop
          command: bundle exec rubocop
      - run:
          name: rspec
          command: bundle exec rspec
