 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/models", type: :request do
  # Model. As you add validations to Model, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Model.create! valid_attributes
      get models_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      model = Model.create! valid_attributes
      get model_url(model)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_model_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      model = Model.create! valid_attributes
      get edit_model_url(model)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Model" do
        expect {
          post models_url, params: { model: valid_attributes }
        }.to change(Model, :count).by(1)
      end

      it "redirects to the created model" do
        post models_url, params: { model: valid_attributes }
        expect(response).to redirect_to(model_url(Model.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Model" do
        expect {
          post models_url, params: { model: invalid_attributes }
        }.to change(Model, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post models_url, params: { model: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested model" do
        model = Model.create! valid_attributes
        patch model_url(model), params: { model: new_attributes }
        model.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the model" do
        model = Model.create! valid_attributes
        patch model_url(model), params: { model: new_attributes }
        model.reload
        expect(response).to redirect_to(model_url(model))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        model = Model.create! valid_attributes
        patch model_url(model), params: { model: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested model" do
      model = Model.create! valid_attributes
      expect {
        delete model_url(model)
      }.to change(Model, :count).by(-1)
    end

    it "redirects to the models list" do
      model = Model.create! valid_attributes
      delete model_url(model)
      expect(response).to redirect_to(models_url)
    end
  end
end
