require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/os_names", type: :request do
  # OsName. As you add validations to OsName, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip("Add a hash of attributes valid for your model")
  end

  let(:invalid_attributes) do
    skip("Add a hash of attributes invalid for your model")
  end

  describe "GET /index" do
    it "renders a successful response" do
      OsName.create! valid_attributes
      get os_names_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      os_name = OsName.create! valid_attributes
      get os_name_url(os_name)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_os_name_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      os_name = OsName.create! valid_attributes
      get edit_os_name_url(os_name)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new OsName" do
        expect do
          post os_names_url, params: { os_name: valid_attributes }
        end.to change(OsName, :count).by(1)
      end

      it "redirects to the created os_name" do
        post os_names_url, params: { os_name: valid_attributes }
        expect(response).to redirect_to(os_name_url(OsName.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new OsName" do
        expect do
          post os_names_url, params: { os_name: invalid_attributes }
        end.to change(OsName, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post os_names_url, params: { os_name: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        skip("Add a hash of attributes valid for your model")
      end

      it "updates the requested os_name" do
        os_name = OsName.create! valid_attributes
        patch os_name_url(os_name), params: { os_name: new_attributes }
        os_name.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the os_name" do
        os_name = OsName.create! valid_attributes
        patch os_name_url(os_name), params: { os_name: new_attributes }
        os_name.reload
        expect(response).to redirect_to(os_name_url(os_name))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        os_name = OsName.create! valid_attributes
        patch os_name_url(os_name), params: { os_name: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested os_name" do
      os_name = OsName.create! valid_attributes
      expect do
        delete os_name_url(os_name)
      end.to change(OsName, :count).by(-1)
    end

    it "redirects to the os_names list" do
      os_name = OsName.create! valid_attributes
      delete os_name_url(os_name)
      expect(response).to redirect_to(os_names_url)
    end
  end
end
